INSERT INTO plant_profiles (
  code,
  name,
  min_temperature,
  max_temperature,
  min_humidity,
  max_humidity,
  min_soil_moisture,
  max_soil_moisture,
  min_light,
  max_light,
  watering_note,
  care_note,
  aliases
) VALUES
(
  'tomato',
  'Cà chua',
  20,
  30,
  50,
  80,
  55,
  75,
  600,
  900,
  'Cà chua cần đất ẩm vừa, không nên để quá khô hoặc úng nước. Nên tưới vào sáng sớm hoặc chiều mát.',
  'Cà chua thích môi trường ấm, nhiều ánh sáng, đất thoát nước tốt. Cần thông gió để hạn chế nấm bệnh.',
  ARRAY['cà chua', 'ca chua', 'tomato']
),
(
  'lettuce',
  'Xà lách',
  15,
  24,
  60,
  80,
  60,
  80,
  400,
  700,
  'Xà lách cần đất ẩm đều, nên tưới nhẹ và thường xuyên.',
  'Xà lách thích thời tiết mát, tránh nắng gắt và nhiệt độ cao.',
  ARRAY['xà lách', 'xa lach', 'lettuce']
),
(
  'strawberry',
  'Dâu tây',
  15,
  26,
  60,
  75,
  55,
  70,
  500,
  800,
  'Dâu tây cần đất ẩm vừa, thoát nước tốt, tránh úng rễ.',
  'Dâu tây thích khí hậu mát, ánh sáng đầy đủ nhưng không quá gắt.',
  ARRAY['dâu tây', 'dau tay', 'strawberry']
),
(
  'mustard_greens',
  'Rau cải',
  18,
  28,
  60,
  80,
  60,
  80,
  400,
  700,
  'Rau cải cần đất ẩm đều, nên tưới nhẹ hằng ngày nếu đất khô.',
  'Rau cải thích khí hậu mát đến ấm, cần ánh sáng vừa đến mạnh.',
  ARRAY['rau cải', 'rau cai', 'cải xanh', 'cai xanh', 'mustard greens']
),
(
  'cucumber',
  'Dưa leo',
  20,
  30,
  60,
  80,
  60,
  80,
  600,
  900,
  'Dưa leo cần đất ẩm đều, không để khô hạn kéo dài nhưng cũng cần thoát nước tốt.',
  'Dưa leo thích môi trường ấm, nhiều ánh sáng và cần giàn leo hoặc không gian thoáng.',
  ARRAY['dưa leo', 'dua leo', 'dưa chuột', 'dua chuot', 'cucumber']
),
(
  'chili',
  'Ớt',
  20,
  32,
  50,
  75,
  45,
  65,
  600,
  900,
  'Ớt cần tưới vừa phải, tránh để đất úng vì dễ gây thối rễ.',
  'Ớt thích nắng và môi trường ấm, đất thoát nước tốt.',
  ARRAY['ớt', 'ot', 'chili', 'chilli', 'pepper']
),
(
  'water_spinach',
  'Rau muống',
  22,
  32,
  60,
  85,
  70,
  90,
  500,
  800,
  'Rau muống cần nhiều nước hơn nhiều loại rau ăn lá khác, nên giữ đất ẩm đều.',
  'Rau muống thích thời tiết ấm, ánh sáng tốt và sinh trưởng nhanh khi đủ nước.',
  ARRAY['rau muống', 'rau muong', 'water spinach']
),
(
  'basil',
  'Húng quế',
  20,
  30,
  50,
  75,
  50,
  70,
  500,
  800,
  'Húng quế cần đất ẩm vừa, tưới khi mặt đất bắt đầu khô.',
  'Húng quế thích nắng nhẹ đến nắng đầy đủ, nên tỉa ngọn để cây phân nhánh tốt.',
  ARRAY['húng quế', 'hung que', 'basil']
),
(
  'mint',
  'Bạc hà',
  18,
  28,
  55,
  80,
  60,
  80,
  400,
  700,
  'Bạc hà thích đất ẩm đều, không nên để khô lâu.',
  'Bạc hà phát triển tốt ở nơi sáng vừa, mát và có thể lan nhanh nếu không kiểm soát.',
  ARRAY['bạc hà', 'bac ha', 'mint']
),
(
  'bok_choy',
  'Cải thìa',
  16,
  26,
  60,
  80,
  60,
  80,
  400,
  700,
  'Cải thìa cần đất ẩm đều, tưới nhẹ để tránh dập lá.',
  'Cải thìa thích khí hậu mát, ánh sáng vừa đến mạnh, tránh nắng gắt kéo dài.',
  ARRAY['cải thìa', 'cai thia', 'bok choy', 'pak choi']
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  min_temperature = EXCLUDED.min_temperature,
  max_temperature = EXCLUDED.max_temperature,
  min_humidity = EXCLUDED.min_humidity,
  max_humidity = EXCLUDED.max_humidity,
  min_soil_moisture = EXCLUDED.min_soil_moisture,
  max_soil_moisture = EXCLUDED.max_soil_moisture,
  min_light = EXCLUDED.min_light,
  max_light = EXCLUDED.max_light,
  watering_note = EXCLUDED.watering_note,
  care_note = EXCLUDED.care_note,
  aliases = EXCLUDED.aliases,
  active = TRUE;
